name: blog-check

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.2.2'

    steps:
      - name: Run setup
        run: make setup

      - name: Run start
        run: |
          bin/setup
          yarn install
          bundle install

      - name: Run start
        run: make start

      - name: Install linters
        run: |
          gem install rubocop
          gem install rubocop-rails
          gem install slim-lint

      - name: Run linters
        run: |
          rubocop
          slim-lint


      - name: Run a multi-line
        run: |
          echo Add otehr
          echo test, and deploy

