name: blog-check

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Rubocop
      #   run: make lint

      - name: Slim-linter
        run: make slim_linter
