name: blog-check

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.2.2'

    steps:
      - name: Run a one-line
        run: echo Hello, World

      - name: Run a multi-line
        run: |
          echo Add otehr
          echo test, and deploy

